spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY:classpath:certs/public.pem}

  sentry:
    dsn: https://12c9bab6868def8642523363055c0e1d@o4507566253801472.ingest.de.sentry.io/4507566258782288
    sentry.traces-sample-rate: 1.0
    sentry.exception-resolver-order: -2147483647